### PR TITLE
AllowedValues on all (primitive) types

### PR DESCRIPTION
**Pull request by ralfhandl**

### CODE REVIEW

**Comment by ralfhandl** [comment]
@chgeo Please review

**Comment by hjboth** [comment]
@ralfhandl would you please add some reviewers?

**Comment by ralfhandl** [comment]
I can't, insufficient privileges for this repo.

**Comment by hjboth** [comment]
@ralfhandl any candidates you'd like to add?

**Comment by ralfhandl** [comment]
You 😎

**Comment by ralfhandl** [comment]
The relevant portions are

https://github.com/cap-js/openapi/blob/3ebb1fce7bf7a6b12cbccf789e977acac929d5f4/test/lib/compile/csdl2openapi.test.js#L2260-L2262

and

https://github.com/cap-js/openapi/blob/3ebb1fce7bf7a6b12cbccf789e977acac929d5f4/test/lib/compile/csdl2openapi.test.js#L2290

proving that integer enums are correctly reflected in OpenAPI

**Review by hjboth — APPROVED** [review]

**Review by Fannon — APPROVED** [review]

**Comment by chgeo** [comment]
> Please review

No, I am no maintainer here.  @RoshniNaveenaS maybe?

**Comment by RoshniNaveenaS** [comment]
Hello @ralfhandl 
I have tested this PR, looks good to me. I will add a changelog entry and this is good to go.

**Pull request merged**
